### ISSUE TITLE
會否加入天氣警告圖示？

### ISSUE THREAD

**Issue by duxing0626** [aes-alienrip/hko-weather-card#2]
例如風球訊號，雷電警告等天氣警告圖示

**Comment by aes-alienrip** [comment]
圖示已經弄好
下一個測試版本會加入熱帶氣旋
並將雷暴警告及暴雨警告入合併到大圖示當中
下圖顯示為紅色暴雨及雷暴警告同時生效
![wrainr-ts](https://github.com/aes-alienrip/hko-weather-card/assets/73251414/dd50a52c-3ea9-41f4-ab8f-763230bf313c)
