### ISSUE TITLE
Missing Weather Icons

### ISSUE THREAD

**Issue by AzNdevil** [aes-alienrip/hko-weather-card#4]
Missing Weather Icons

Version 1.1.7b

Seems theres something wrong with the icon name generation after updating. It's fine on 1.1.8

![image](https://github.com/aes-alienrip/hko-weather-card/assets/57991417/4bf42ccc-0aee-4761-a69b-ed613ee388dc)
![image](https://github.com/aes-alienrip/hko-weather-card/assets/57991417/48e8afa2-1e5f-4092-8ee7-1adca20cb385)

**Comment by aes-alienrip** [comment]
Both 1.1.7b and 1.1.8 rename fair-day-rain to light-showers already, maybe lovelace js resource caching issue?
Btw next release will update the svg again to fix svg looks blurry in ios safari

**Comment by aes-alienrip** [comment]
And i am not aware that forecast psr string is too long in english sensor, maybe Med High / M Low in single line looks better?
